repos:
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    -   id: pretty-format-kotlin
        args: [--autofix]
-   repo: local
    hooks:
    -   id: build-android
        name: Build Android
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew assembleDebug assembleRelease --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: build-ios
        name: Build iOS
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew compileKotlinIosArm64 compileKotlinIosSimulatorArm64 --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: build-jvm
        name: Build JVM
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew compileKotlinJvm --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: build-web
        name: Build Web
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew compileKotlinJs compileKotlinWasmJs --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: test
        name: Test
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew allTests --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: lint
        name: Lint
        entry: env NODE_OPTIONS="--max-old-space-size=8192" ./gradlew lint --no-daemon
        language: system
        files: \.(kt|kts|java|xml|gradle|toml)$
        pass_filenames: false
    -   id: check-env-leaks
        name: Check for .env leaks
        entry: python3 scripts/check_env_leaks.py
        language: system
        pass_filenames: true
    -   id: doc-test-coverage
        name: Update Doc and Test Coverage Badges
        entry: python3 scripts/check_coverage.py
        language: system
        pass_filenames: false
