#Kotlin
kotlin.code.style=official
kotlin.daemon.jvm.options=-Xmx20g
kotlin.native.jvm.options=-Xmx20g
kotlin.native.jvmArgs=-Xmx20g
org.jetbrains.kotlin.native.jvmArgs=-Xmx20g

#Gradle
org.gradle.jvmargs=-Xmx20g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

kotlin.native.disableCompilerDaemon=true
