"""
This module provides a script to verify that a project's test coverage meets a 100%
threshold. It parses an XML coverage report (typically generated by Kover or JaCoCo)
and evaluates various coverage metrics such as instruction, branch, line, and method
coverage.
"""

import os
import sys
import xml.etree.ElementTree as ET


def check_coverage(xml_path):
    """
    Parse a coverage XML report and verify that all coverage metrics are at 100%.

    This function reads the specified XML report and looks for `<counter>` elements
    at the root level. For specific metric types ('INSTRUCTION', 'BRANCH', 'LINE',
    'METHOD'), it calculates the coverage percentage based on the 'missed' and
    'covered' attributes. If any evaluated metric falls below 100.0%, it prints an
    error and marks the check as failed.

    :param xml_path: The file path to the coverage XML report.
    :type xml_path: str
    :return: True if the file exists and all evaluated coverage metrics are at exactly
             100.0% (or if there are no items to cover). False otherwise.
    :rtype: bool
    """
    if not os.path.exists(xml_path):
        print(f"Coverage report not found at {xml_path}")
        # To avoid failing the overall flow if kover hasn't run yet, but the instruction is to parse it
        return False

    tree = ET.parse(xml_path)
    root = tree.getroot()

    # The root element is usually <report>
    # Find the overall <counter> elements at the root level (or compute if not present)
    overall_counters = root.findall("./counter")

    passed = True
    for counter in overall_counters:
        ctype = counter.get("type")
        if ctype in ["INSTRUCTION", "BRANCH", "LINE", "METHOD"]:
            missed = int(counter.get("missed"))
            covered = int(counter.get("covered"))
            total = missed + covered
            if total > 0:
                percent = (covered / total) * 100
                print(f"{ctype} coverage: {percent:.2f}%")
                if percent < 100.0:
                    print(f"Error: {ctype} coverage is below 100.0% ({percent:.2f}%)")
                    passed = False
            else:
                print(f"{ctype} coverage: 100.0% (No items)")

    return passed


if __name__ == "__main__":
    # Typically kover generates something like build/reports/kover/report.xml
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    xml_path = os.path.join(project_root, "chartCam/build/reports/kover/report.xml")

    if os.path.exists(xml_path):
        if not check_coverage(xml_path):
            sys.exit(1)
        print("Test coverage is 100.0%")
        sys.exit(0)
    else:
        # Fallback to stub if no report is present so we don't break local runs unexpectedly
        # But wait, the instruction says "instead of stubbing 100.0% success."
        print(
            f"Could not find {xml_path}. Assuming tests did not run or coverage report missing."
        )
        sys.exit(1)
